# Generated by Django 3.2.7 on 2021-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyTestModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("test", models.CharField(max_length=100)),
            ],
        ),
    ]
